micronaut:
    application:
        name: configissue
                
#Uncomment to set server port
#    server:
#        port: 8080
    codec:
        json:
            additionalTypes:
                - "text/javascript"